# nginx proxy address - http://172.17.0.1:59129

name: gitlab
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    shm_size: 4g
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${BASE_HOST_NAME:-$HOSTNAME}'
        gitlab_rails['time_zone'] = '${TZ:-America/New_York}'
        gitlab_rails['initial_root_password'] = '${APP_ADMIN_PASS:-changeme_admin_password}'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = '${EMAIL_SERVER_HOST:-172.17.0.1}'
        gitlab_rails['smtp_port'] = ${EMAIL_SERVER_PORT:-587}
        gitlab_rails['smtp_user_name'] = '${EMAIL_SERVER_USER:-}'
        gitlab_rails['smtp_password'] = '${EMAIL_SERVER_PASS:-}'
        gitlab_rails['smtp_domain'] = '${BASE_DOMAIN_NAME:-example.com}'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['gitlab_email_from'] = '${EMAIL_SERVER_MAIL_FROM:-noreply@example.com}'
        gitlab_rails['gitlab_email_reply_to'] = '${EMAIL_SERVER_MAIL_FROM:-noreply@example.com}'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
    ports:
      - '2223:22'
      - '172.17.0.1:59129:80'
    volumes:
      - './volumes/config/gitlab:/etc/gitlab'
      - './volumes/data/log/gitlab:/var/log/gitlab'
      - './volumes/data/gitlab:/var/opt/gitlab'
    networks:
      - gitlab

networks:
  gitlab:
    name: gitlab
    external: false
